(()=>{'use strict';
const $=s=>document.querySelector(s),cfg=window.WEDDING_APP_CONFIG||{},EVENT_ID=cfg.eventId||'shu-qiu-2026',LOGIN_EMAIL='checkin@shuping-qiuhua.com';
let db,session,realtime,timer,selected=null;const state={tables:[],guests:[]};
const el={auth:$('#authShell'),app:$('#app'),form:$('#loginForm'),pw:$('#loginPassword'),login:$('#loginBtn'),msg:$('#authMsg'),logout:$('#logoutBtn'),status:$('#liveStatus'),q:$('#guestSearch'),clear:$('#clearSearch'),sug:$('#searchSuggestions'),result:$('#guestResult'),name:$('#resultName'),table:$('#resultTable'),meta:$('#resultMeta'),again:$('#searchAgain'),map:$('#venueMap'),tables:$('#mapTables'),caption:$('#mapCaption')};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),norm=v=>String(v??'').trim().replace(/\s+/g,' ').toLowerCase(),table=id=>state.tables.find(t=>t.id===id);
function setStatus(t,tone='ok'){el.status.textContent=t;el.status.dataset.tone=tone}function configOK(){return /^https:\/\/.+\.supabase\.co$/i.test(cfg.supabaseUrl||'')&&/^sb_publishable_/.test(cfg.supabasePublishableKey||'')}
async function init(){if(!window.supabase?.createClient||!configOK()){el.msg.textContent='系統設定尚未完成';el.login.disabled=true;return}db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true}});bind();const{data}=await db.auth.getSession();if(data?.session)await open(data.session);db.auth.onAuthStateChange((e,s)=>{if(e==='SIGNED_OUT')showLogin();if(e==='SIGNED_IN'&&s&&s.user.id!==session?.user?.id)open(s)})}
function showLogin(m=''){session=null;if(realtime)db.removeChannel(realtime);realtime=null;el.app.hidden=true;el.auth.hidden=false;el.msg.textContent=m;el.pw.value=''}
async function open(s){session=s;el.msg.textContent='確認權限…';try{const[o,st]=await Promise.all([db.from('event_members').select('role').eq('event_id',EVENT_ID).eq('user_id',s.user.id).maybeSingle(),db.from('wedding_checkin_staff').select('user_id').eq('event_id',EVENT_ID).eq('user_id',s.user.id).maybeSingle()]);if(!(!o.error&&o.data?.role==='owner')&&!(!st.error&&st.data)){await db.auth.signOut();return showLogin('這組密碼沒有帶位查位權限')}await load();el.auth.hidden=true;el.app.hidden=false;subscribe();setTimeout(()=>el.q.focus(),80)}catch(e){console.error(e);el.msg.textContent='暫時無法讀取座位資料'}}
async function load(){setStatus('同步中…','busy');const[t,g]=await Promise.all([db.from('wedding_tables').select('id,name,sort_order').eq('event_id',EVENT_ID).order('sort_order'),db.from('wedding_guests').select('id,name,party_size,companions,table_id,attendance,sort_order').eq('event_id',EVENT_ID).eq('attendance','dinner').order('sort_order')]);if(t.error||g.error){setStatus('讀取失敗','error');throw(t.error||g.error)}state.tables=t.data||[];state.guests=g.data||[];renderMap();if(selected)selectGuest(selected,false);setStatus('座位已同步')}
function subscribe(){realtime=db.channel('usher-'+EVENT_ID).on('postgres_changes',{event:'*',schema:'public',table:'wedding_guests'},reload).on('postgres_changes',{event:'*',schema:'public',table:'wedding_tables'},reload).subscribe()}function reload(){clearTimeout(timer);timer=setTimeout(()=>load().catch(console.error),180)}
function rank(g,q){const n=norm(g.name),c=norm(g.companions),t=norm(table(g.table_id)?.name);return n.startsWith(q)?0:n.includes(q)?1:c.includes(q)?2:t.includes(q)?3:99}
function search(){const q=norm(el.q.value);el.clear.hidden=!q;if(!q)return closeSug();const rows=state.guests.filter(g=>rank(g,q)<99).sort((a,b)=>rank(a,q)-rank(b,q)||norm(a.name).localeCompare(norm(b.name),'zh-Hant')).slice(0,12);el.sug.innerHTML=rows.length?rows.map(g=>{const t=table(g.table_id);return `<button type="button" data-id="${g.id}"><span><b>${esc(g.name)}</b>${g.companions?`<small>同行：${esc(g.companions)}</small>`:''}</span><strong>${esc(t?.name||'尚未分桌')}</strong></button>`}).join(''):`<div class="no-result">找不到「${esc(el.q.value)}」<small>可只輸入姓名其中一個字</small></div>`;el.sug.hidden=false;el.q.setAttribute('aria-expanded','true');el.sug.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>selectGuest(b.dataset.id,true))}
function closeSug(){el.sug.hidden=true;el.q.setAttribute('aria-expanded','false')}
function selectGuest(id,scroll=true){const g=state.guests.find(x=>x.id===id);if(!g)return;selected=id;const t=table(g.table_id);el.q.value=g.name;el.clear.hidden=false;closeSug();el.q.blur();el.name.textContent=g.name;el.table.textContent=t?.name||'尚未分桌';el.meta.textContent=[g.companions?`同行：${g.companions}`:'',`共 ${+g.party_size||1} 位`].filter(Boolean).join('　');el.result.hidden=false;renderMap(t?.id);el.caption.textContent=t?`已標示：${t.name}`:'此來賓尚未分桌';if(scroll)setTimeout(()=>el.result.scrollIntoView({behavior:'smooth',block:'start'}),70)}
function reset(){selected=null;el.q.value='';el.clear.hidden=true;el.result.hidden=true;closeSug();renderMap();el.caption.textContent='選到來賓後，對應桌次會在圖上亮起來';setTimeout(()=>el.q.focus(),20)}
const spots=['main','1','2','3','5','6','7','8','9','10','11','12','13','14','15','16','17','reserve'];
function key(t,i){const n=String(t.name||'');if(n.includes('主桌'))return'main';if(n.includes('預備'))return'reserve';const m=n.match(/(?:^|\D)(0?[1-9]|1[0-7])\s*桌/);return m?String(parseInt(m[1],10)):(spots[i]||String(i+1))}
function label(t,k){if(k==='main'||k==='reserve')return[k==='main'?'主桌':'預備桌',''];const num=String(k).padStart(2,'0')+'桌';let sub=String(t.name||'').replace(new RegExp('^0?'+parseInt(k,10)+'\\s*桌\\s*[｜|·・:\\-]?\\s*'),'').trim();if(sub===num)sub='';return[num,sub]}
function renderMap(highlight){const used=new Set();el.tables.innerHTML=state.tables.map((t,i)=>{let k=key(t,i);if(used.has(k))k=spots[i]||k;used.add(k);const[n,s]=label(t,k),on=highlight&&t.id===highlight;return `<div class="map-table spot-${k}${on?' active':''}" title="${esc(t.name)}"><b>${esc(n)}</b>${s?`<span>${esc(s)}</span>`:''}</div>`}).join('');el.map.classList.toggle('has-selection',!!highlight)}
function bind(){el.form.onsubmit=async e=>{e.preventDefault();el.login.disabled=true;el.msg.textContent='登入中…';const{data,error}=await db.auth.signInWithPassword({email:LOGIN_EMAIL,password:el.pw.value});el.login.disabled=false;if(error){el.msg.textContent='密碼不正確，請再試一次';el.pw.select();return}if(data?.session)await open(data.session)};el.logout.onclick=async()=>{await db.auth.signOut();showLogin()};el.q.oninput=search;el.q.onfocus=()=>{if(norm(el.q.value))search()};el.clear.onclick=reset;el.again.onclick=reset;document.addEventListener('pointerdown',e=>{if(!e.target.closest('.search-combobox'))closeSug()})}
init();})();
